updated

diff --git a/0x08-networking_basics_2/0-change_your_home_IP b/0x08-networking_basics_2/0-change_your_home_IP
--- a/0x08-networking_basics_2/0-change_your_home_IP
+++ b/0x08-networking_basics_2/0-change_your_home_IP
@@ -1,9 +1,22 @@
 #!/usr/bin/env bash
-# Config a Ubuntu server to:
-# localhost resolves to 127.0.0.2
-# facebook resolves to 8.8.8.8
+#
+# Configure resolution of localhost to 127.0.0.2 and facebook.com to 8.8.8.8
 
-cp /etc/hosts ~/temp
-sed -i s/127.0.0.1/127.0.0.2/ ~/temp
-echo "8.8.8.8 facebook.com" >> ~/temp
-cp -f ~/temp /etc/hosts
+if (( ${UID:-$(id -u)} ))
+then
+  echo 'Must be run as root'
+  exit 1
+fi
+
+if ! tempfile="$(mktemp)"
+then
+  echo 'Unable to create temporary file'
+  exit 1
+fi
+
+{ printf '%s\t%s\n' 127.0.0.2 localhost
+  printf '%s\t%s\n' 8.8.8.8   facebook.com
+  cat /etc/hosts
+} > "${tempfile}"
+
+cat -- "${tempfile}" > /etc/hosts
